name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ubicar carpeta del proyecto Flutter
        run: |
          TARGET_DIR=$(find . -maxdepth 3 -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "PROJECT_PATH=$TARGET_DIR" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generar Keystore e Imprimir SHA
        run: |
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          echo "=================================================="
          echo "HUELLAS DIGITALES (SHA-1 Y SHA-256):"
          echo "=================================================="
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
          echo "=================================================="

      - name: Generar carpeta Android y dependencias
        run: |
          cd ${{ env.PROJECT_PATH }}
          flutter create . --platforms android
          flutter pub get

      - name: Compilar APK Debug
        run: |
          cd ${{ env.PROJECT_PATH }}
          flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/app/outputs/flutter-apk/app-debug.apk"
